### ISSUE TITLE
directoryCreate

### ISSUE THREAD

**Issue by guerino-tutuka** [foundeo/cfdocs#1445]
The attribute `ignoreExists` only works doesn't works for ColdFusion and it's not marked as Lucee Only

![image](https://user-images.githubusercontent.com/91262037/148782177-fb26b6ad-a3dd-4d4a-8891-7d99d1968e5b.png)

Running the bellow code, this exception is thrown

```
<cfscript>
	directoryCreate(dirPath, true);
</cfscript>
```
**Exception**
```
coldfusion.compiler.validation.FunctionArgMismatchException: Parameter validation error for the DIRECTORYCREATE function.
	at coldfusion.compiler.validation.FunctionValidator.checkArgCount(FunctionValidator.java:96)
	at coldfusion.compiler.validation.CFMLCodeValidator.visit(CFMLCodeValidator.java:195)
	at coldfusion.compiler.ASTruntimeCall.accept(ASTruntimeCall.java:521)
	at coldfusion.compiler.ASTcfscriptStatement.accept(ASTcfscriptStatement.java:131)
	at coldfusion.compiler.Node.walkChildren(Node.java:394)
	at coldfusion.compiler.ASTcfscript.accept(ASTcfscript.java:17)
	at coldfusion.compiler.Node.walkChildren(Node.java:394)
	at coldfusion.compiler.ASTstart.accept(ASTstart.java:122)
	at coldfusion.compiler.NeoTranslator.validate(NeoTranslator.java:602)
	at coldfusion.compiler.NeoTranslator.parseAndTransform(NeoTranslator.java:469)
	at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:407)
	at coldfusion.compiler.NeoTranslator.translateJava(NeoTranslator.java:160)
	at coldfusion.runtime.TemplateClassLoader$TemplateCache$1.fetch(TemplateClassLoader.java:484)
	at coldfusion.util.LruCache.get(LruCache.java:180)
	at coldfusion.runtime.TemplateClassLoader$TemplateCache.fetchSerial(TemplateClassLoader.java:404)
	at coldfusion.util.AbstractCache.fetch(AbstractCache.java:58)
	at coldfusion.util.SoftCache.get_statsOff(SoftCache.java:153)
	at coldfusion.util.SoftCache.get(SoftCache.java:92)
	at coldfusion.runtime.TemplateClassLoader.findClass(TemplateClassLoader.java:685)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:145)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:45)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:96)
	at coldfusion.filter.BrowserDebugFilter.invoke(BrowserDebugFilter.java:78)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:60)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:226)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:311)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:46)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:47)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:373)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Official CF documentation: https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-c-d/DirectoryCreate.html

**Comment by pfreitag** [comment]
Thanks for the detailed report @guerino-tutuka! This has been fixed.
